//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 04:44:57 PM CET 
//


package fr.emac.gipsi.gsi.truptil.equipe;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="numGroupe" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="numEquipe" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "position")
public class Position {

    @XmlAttribute(name = "numGroupe")
    protected Integer numGroupe;
    @XmlAttribute(name = "numEquipe")
    protected Integer numEquipe;

    /**
     * Gets the value of the numGroupe property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumGroupe() {
        return numGroupe;
    }

    /**
     * Sets the value of the numGroupe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumGroupe(Integer value) {
        this.numGroupe = value;
    }

    /**
     * Gets the value of the numEquipe property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumEquipe() {
        return numEquipe;
    }

    /**
     * Sets the value of the numEquipe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumEquipe(Integer value) {
        this.numEquipe = value;
    }

}
