
package pronostic.util.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PronostiqueService", targetNamespace = "http://www.emac.fr/pronostique/", wsdlLocation = "http://localhost:9001/PronostiqueEndpoint?wsdl")
public class PronostiqueService
    extends Service
{

    private final static URL PRONOSTIQUESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRONOSTIQUESERVICE_EXCEPTION;
    private final static QName PRONOSTIQUESERVICE_QNAME = new QName("http://www.emac.fr/pronostique/", "PronostiqueService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9001/PronostiqueEndpoint?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRONOSTIQUESERVICE_WSDL_LOCATION = url;
        PRONOSTIQUESERVICE_EXCEPTION = e;
    }

    public PronostiqueService() {
        super(__getWsdlLocation(), PRONOSTIQUESERVICE_QNAME);
    }

    public PronostiqueService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRONOSTIQUESERVICE_QNAME, features);
    }

    public PronostiqueService(URL wsdlLocation) {
        super(wsdlLocation, PRONOSTIQUESERVICE_QNAME);
    }

    public PronostiqueService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRONOSTIQUESERVICE_QNAME, features);
    }

    public PronostiqueService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PronostiqueService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PronostiqueInterface
     */
    @WebEndpoint(name = "PronostiqueSOAP")
    public PronostiqueInterface getPronostiqueSOAP() {
        return super.getPort(new QName("http://www.emac.fr/pronostique/", "PronostiqueSOAP"), PronostiqueInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PronostiqueInterface
     */
    @WebEndpoint(name = "PronostiqueSOAP")
    public PronostiqueInterface getPronostiqueSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.emac.fr/pronostique/", "PronostiqueSOAP"), PronostiqueInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRONOSTIQUESERVICE_EXCEPTION!= null) {
            throw PRONOSTIQUESERVICE_EXCEPTION;
        }
        return PRONOSTIQUESERVICE_WSDL_LOCATION;
    }

}
