//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 04:40:20 PM CET 
//


package fr.emac.gipsi.gsi.truptil.extract;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="equipe1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="equipe2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="score1" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="score2" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "match")
public class Match {

    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "equipe1")
    protected String equipe1;
    @XmlAttribute(name = "equipe2")
    protected String equipe2;
    @XmlAttribute(name = "score1")
    protected Integer score1;
    @XmlAttribute(name = "score2")
    protected Integer score2;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the equipe1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipe1() {
        return equipe1;
    }

    /**
     * Sets the value of the equipe1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipe1(String value) {
        this.equipe1 = value;
    }

    /**
     * Gets the value of the equipe2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipe2() {
        return equipe2;
    }

    /**
     * Sets the value of the equipe2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipe2(String value) {
        this.equipe2 = value;
    }

    /**
     * Gets the value of the score1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getScore1() {
        return score1;
    }

    /**
     * Sets the value of the score1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScore1(Integer value) {
        this.score1 = value;
    }

    /**
     * Gets the value of the score2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getScore2() {
        return score2;
    }

    /**
     * Sets the value of the score2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScore2(Integer value) {
        this.score2 = value;
    }

}
