package fr.emac.calcul;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-30T18:45:03.629+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "CalculService", 
                  wsdlLocation = "file:/C:/Users/PGM/workspace/java-gsi/GIPSI-DWJ-pgirault-aballet/WSCalcul1/src/main/resources/wsdl/calcul.wsdl",
                  targetNamespace = "http://www.emac.fr/calcul/") 
public class CalculService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.emac.fr/calcul/", "CalculService");
    public final static QName CalculSOAP = new QName("http://www.emac.fr/calcul/", "CalculSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/PGM/workspace/java-gsi/GIPSI-DWJ-pgirault-aballet/WSCalcul1/src/main/resources/wsdl/calcul.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/PGM/workspace/java-gsi/GIPSI-DWJ-pgirault-aballet/WSCalcul1/src/main/resources/wsdl/calcul.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CalculService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CalculInterface
     */
    @WebEndpoint(name = "CalculSOAP")
    public CalculInterface getCalculSOAP() {
        return super.getPort(CalculSOAP, CalculInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculInterface
     */
    @WebEndpoint(name = "CalculSOAP")
    public CalculInterface getCalculSOAP(WebServiceFeature... features) {
        return super.getPort(CalculSOAP, CalculInterface.class, features);
    }

}
