package fr.emac.calcul;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-30T18:45:03.561+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://www.emac.fr/calcul/", name = "CalculInterface")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CalculInterface {

    @WebMethod(action = "http://www.emac.fr/calcul/calculerPointsJoueur")
    @WebResult(name = "calculerPointsJoueurResponse", targetNamespace = "http://www.emac.fr/calcul/", partName = "parameters")
    public CalculerPointsJoueurResponse calculerPointsJoueur(
        @WebParam(partName = "parameters", name = "calculerPointsJoueurInput", targetNamespace = "http://www.emac.fr/calcul/")
        CalculerPointsJoueurInput parameters
    );
}
