
package fr.emac.calcul;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-30T18:45:03.589+01:00
 * Generated source version: 3.1.4
 * 
 */
 
public class CalculInterface_CalculSOAP_Server{

    protected CalculInterface_CalculSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CalculSOAPImpl();
        String address = "http://localhost:9002/CalculEndpoint";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CalculInterface_CalculSOAP_Server();
        System.out.println("Server ready..."); 
        
//        Thread.sleep(5 * 60 * 1000)		; 
//        System.out.println("Server exiting");
//        System.exit(0);
    }
}
