
package calcul.util.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculInterface", targetNamespace = "http://www.emac.fr/calcul/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculInterface {


    /**
     * 
     * @param parameters
     * @return
     *     returns calcul.util.client.CalculerPointsJoueurResponse
     */
    @WebMethod(action = "http://www.emac.fr/calcul/calculerPointsJoueur")
    @WebResult(name = "calculerPointsJoueurResponse", targetNamespace = "http://www.emac.fr/calcul/", partName = "parameters")
    public CalculerPointsJoueurResponse calculerPointsJoueur(
        @WebParam(name = "calculerPointsJoueurInput", targetNamespace = "http://www.emac.fr/calcul/", partName = "parameters")
        CalculerPointsJoueurInput parameters);

}
